server:
#  port: 8003
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
#      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#spring:
#  application:
#    zipkin: http://localhost:9412
spring:
  zipkin:
    base-url: http://localhost:9412
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0