server:
  port: 8081
spring:
  cloud:
    config:
      server: 
        git:
#         default-label: config-servie
#         default-label: instances
          default-label: gateway
          uri: https://github.com/gdelucca/microservicios
          search-paths: config-data
  application:
    name: config-service